# Generated by Django 4.2.5 on 2025-06-23 08:34

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('exam_app', '0003_exam_studentanswer_result'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='exam',
            options={'ordering': ['-date_taken']},
        ),
        migrations.AlterUniqueTogether(
            name='exam',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='course',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='course',
            name='time_limit_minutes',
            field=models.PositiveIntegerField(default=60, help_text='Time limit for the exam in minutes (e.g., 60 for 1 hour).', validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(240)]),
        ),
        migrations.AddField(
            model_name='course',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(default=1, limit_choices_to={'is_teacher': True}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('name', 'teacher')},
        ),
        migrations.RemoveField(
            model_name='course',
            name='total_marks',
        ),
        migrations.RemoveField(
            model_name='course',
            name='total_questions',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='score',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='total_possible_marks',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='total_questions',
        ),
    ]
