# Generated by Django 4.2.5 on 2025-06-26 12:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam_app', '0006_question_question_type_alter_question_choice1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('date_set', models.DateTimeField(auto_now_add=True)),
                ('teacher', models.OneToOneField(limit_choices_to={'approved': True, 'is_teacher': True}, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_salary', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Salaries',
                'ordering': ['-date_set'],
            },
        ),
    ]
